### ISSUE TITLE
Redis Icon broken in Service Catalog

### ISSUE THREAD

**Issue by kautsig** [kyma-project/bundles#60]
**Description**

I create a fresh kyma cluster from scratch, based on version 0.6.1.

I opened the service catalog in a pre-defined namespace.

**Expected result**

The local redis service is shown. The redis icon is shown right next to the service.

**Actual result**

The icons is missing.

The image is embedded from an external URL, which seems to return 200, but does not return any svg data.

**Steps to reproduce**

- Setup a fresh kyma cluster, 0.6.1 based on minikube
- Access the service catalog

Alternative: 

- Try to access https://azure.microsoft.com/svghandler/redis-cache/

**Troubleshooting**

I searched the repo for the non-working URL. It's probably taken from:

https://github.com/kyma-project/bundles/blob/latest/bundles/redis-0.0.3/meta.yaml#12

**Comment by kautsig** [comment]
![image](https://user-images.githubusercontent.com/1544008/52275645-6f1ffa80-2950-11e9-87a2-feb33182149b.png)

**Comment by derberg** [comment]
just a side comment, due to the issue with the source of the icon, that it responds with 200 OK we cannot do here to much and for now from UI perspective we are just hiding the default browser broken image icon
![screen shot 2019-02-05 at 14 16 22](https://user-images.githubusercontent.com/6995927/52275787-cb831a00-2950-11e9-8c52-ce4dd947cd1e.png)
This fix will be a part of 0.7 release which is scheduled for 11.02, next Monday

**Comment by PK85** [comment]
Hi, we will address that issue soon. We use azure-broker URL and whole broker has missing Images.

**Comment by kautsig** [comment]
Can confirm this fixed. As described above the icon is still missing, but it's included in way that there is no broken image shown.

**Comment by PK85** [comment]
hi, issue has been solved and available with Kyma v1.0.0. Cheers
